### ISSUE TITLE
HEREDOCS generally ugly

### ISSUE THREAD

**Issue by practicingruby** [bglusman/Outlaw#2]
Hi Brian,

Outlaw shouldn't be whitespace sensitive, right? If not, I'd prefer to see you write your tests this way, even if it means a few extra levels of indentation:

``` ruby
before do
  @okay_file = %{
    class Whatever < Set
      def okaything(here)
        @here = here
      end
     end

    module WithContent
      def sumthin
        class_eval('1 + 1')
      end
    end
  }
end
```

Personally, except for in pretty rare circumstances, I stopped using heredocs when I stopped using perl, because I find Ruby's `%{ ... }` syntax to be much less noisy. That said, if I were to use heredocs here and wasn't worried about extra whitespace, I'd use `<<-CODE` instead of `<<CODE` because then you could align the ending tag similar to how I've aligned the } above.

Please make this revision and let me know if you have questions, or if the whitespace might be a concern. If it is, we'll need to find another way to solve this problem. A valid alternative is to use fixture files, which Andrea mentioned in her review.

**Comment by bglusman** [comment]
Fixed...  whitespace is not currently an issue, good call
